services:
  tritonBLAS-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: tritonblas-dev:latest
    container_name: tritonBLAS-dev
    network_mode: "host"
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    shm_size: "16g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - ${HOME}:${HOME}
      - ./:/workspace
    environment:
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no
    working_dir: /workspace
    tty: true
    stdin_open: true
